# Generated by Django 6.0.5 on 2026-05-25 00:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_promocode_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='completion_deadline',
            field=models.DateField(blank=True, null=True, verbose_name='Срок выполнения'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата договора'),
        ),
        migrations.AddField(
            model_name='order',
            name='contract_number',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Номер договора'),
        ),
    ]
